# Query 1: Fetch a list of all active users with their IDs and names
get_projects_from_workbook:
  query: |
    {
      workbooks {
        projectuid
        projectname
      }
    }

# Query 2: Retrieve detailed information about workbooks, including owner, views, and data sources.
master_query:
  query: |
    {
      workbooks(filter : {projectName : project_name_val , projectuid : project_id_val }) {
        id
        name
        projectuid
        projectName
        uri
        createdAt
        updatedAt
        owner {
          id
          name
          username
          email
          createdAt
          updatedAt
        }
        views {
          id
          name
          __typename
          createdAt
          updatedAt
          path
        }
        upstreamDatasources {
          id
          name
          uri
          hasExtracts
          extractLastRefreshTime
          upstreamDatabases {
            name
            __typename
            connectionType
          }
        }
        embeddedDatasources {
          id
          name
          hasExtracts
          extractLastRefreshTime
          upstreamDatabases {
            name
            __typename
            connectionType
          }
        }
        embeddedDatasourcesConnection {
          totalCount
        }
        tags {
          id
          name
        }
      }
    }