logger:
  logger_name: tableau_logger1
  log_level: INFO
  log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  log_dir: logs1
  log_file_name: app1.log
  file_log_level: INFO
  console_log_level: INFO
  logging_enabled: true
  console_logging: disable
